import { Text } from "@chakra-ui/layout";
import { ListItem, UnorderedList } from "@chakra-ui/react";

const Lineup1 = () => {
  return (
    <>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
    </>
  );
};

const Lineup1_en = () => {
  return (
    <>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
    </>
  );
};

const Lineup2 = () => {
  return (
    <>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
    </>
  );
};

const Lineup3 = () => {
  return (
    <>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <UnorderedList>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
      </UnorderedList>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <UnorderedList>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
      </UnorderedList>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
    </>
  );
};

const Lineup4 = () => {
  return (
    <>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>

      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>

      <UnorderedList>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <UnorderedList>
          <ListItem>
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO
          </ListItem>
          <ListItem>
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO
          </ListItem>
        </UnorderedList>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <UnorderedList>
          <ListItem>
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO
          </ListItem>
        </UnorderedList>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <UnorderedList>
          <ListItem>
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO
          </ListItem>
        </UnorderedList>
      </UnorderedList>
    </>
  );
};

const Lineup4_en = () => {
  return (
    <>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>

      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>

      <UnorderedList>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <UnorderedList>
          <ListItem>
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO
          </ListItem>
          <ListItem>
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO
          </ListItem>
        </UnorderedList>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <UnorderedList>
          <ListItem>
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO
          </ListItem>
        </UnorderedList>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <UnorderedList>
          <ListItem>
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
            TODO TODO TODO TODO TODO
          </ListItem>
        </UnorderedList>
      </UnorderedList>
    </>
  );
};

const Lineup5 = () => {
  return (
    <>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
      <UnorderedList>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
        <ListItem>
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
          TODO TODO TODO
        </ListItem>
      </UnorderedList>
    </>
  );
};

const Lineup6 = () => {
  return (
    <>
      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>

      <Text pb={4}>
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO TODO
        TODO TODO TODO
      </Text>
    </>
  );
};

const Lineup7 = () => {
  return (
    <>
      <Text pb={4} />
    </>
  );
};

export const LineupDatabaseJa = [
  {
    id: 1,
    component: Lineup1,
  },
  {
    id: 2,
    component: Lineup2,
  },
  {
    id: 3,
    component: Lineup3,
  },
  {
    id: 4,
    component: Lineup4,
  },
  {
    id: 5,
    component: Lineup5,
  },
  {
    id: 6,
    component: Lineup6,
  },
  {
    id: 7,
    component: Lineup7,
  },
];

export const LineupDatabaseEn = [
  {
    id: 1,
    component: Lineup1_en,
  },
  {
    id: 2,
    component: Lineup2,
  },
  {
    id: 3,
    component: Lineup3,
  },
  {
    id: 4,
    component: Lineup4_en,
  },
  {
    id: 5,
    component: Lineup5,
  },
  {
    id: 6,
    component: Lineup6,
  },
  {
    id: 7,
    component: Lineup7,
  },
];
